name: Déploiement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Remplacer le placeholder dans le script
        env:
          SECRET_API_KEY: ${{ secrets.EMAILJSKEY }}
        run: |
          sed -i "s|API_KEY_PLACEHOLDER|$SECRET_API_KEY|g" email.js

      - name: Déployer
        run: |
          # Commandes pour déployer ton projet
          echo "Déploiement..."
